import type { Salon } from './types'

export const SITE = {
  name: 'stikini',
  nameAr: 'ستيكيني',
  tagline: 'منصة الحجوزات الذكية للصالونات ومحال الحلاقة',
  city: 'الجزائر العاصمة',
  cityFull: 'الجزائر العاصمة، الجزائر',
  address: 'شارع ديدوش مراد، الجزائر الوسطى، الجزائر العاصمة',
  phone: '0550 12 34 56',
  phone2: '0661 78 90 12',
  email: 'contact@stikini.dz',
  supportEmail: 'support@stikini.dz',
  hours: 'السبت إلى الخميس: 9:00 - 19:00',
  whatsapp: '213550123456',
}

/** أكواد الخصم المتاحة عند الحجز (نسبة مئوية من مجموع الخدمات) */
export const PROMO_CODES: Record<string, { percent: number; label: string }> = {
  MAISON10: { percent: 10, label: 'خصم 10%' },
  PRESTIGE15: { percent: 15, label: 'خصم 15%' },
}

export const calcPromoDiscount = (code: string | undefined, subtotal: number): number => {
  if (!code) return 0
  const promo = PROMO_CODES[code.trim().toUpperCase()]
  if (!promo) return 0
  return Math.round((subtotal * promo.percent) / 100)
}

export const NEIGHBORHOODS = [
  'الجزائر الوسطى',
  'حيدرة',
  'الأبيار',
  'بوزريعة',
  'درارية',
  'الشراقة',
  'باب الزوار',
  'الرويبة',
  'الحراش',
  'القبة',
  'كولوش',
  'برج الكيفان',
  'بئر مراد رايس',
  'وادي السمار',
  'الدار البيضاء',
  'عين البنيان',
  'زرالدة',
  'المرسى',
]

export const SALONS: Salon[] = [
  {
    id: 'prestige-hydra',
    slug: 'prestige-hydra',
    name: 'صالون بريستيج حيدرة',
    tagline: 'أناقة رجالية فاخرة في قلب حيدرة',
    description:
      'صالون رجالي فاخر في حي حيدرة الراقي، يقدم خدمات الحلاقة الحديثة والعناية بالذقن والبشرة باستخدام أفضل المنتجات العالمية، مع فريق محترف وأجواء مريحة تليق بك.',
    type: 'رجالية',
    neighborhood: 'حيدرة',
    address: 'شارع العربي بن مهيدي، حيدرة، الجزائر العاصمة',
    phone: '0550 12 34 56',
    rating: 4.9,
    reviewsCount: 342,
    priceLevel: 3,
    image: '/images/salon-1.jpg',
    gallery: ['/images/salon-1.jpg', '/images/style-1.jpg', '/images/style-2.jpg', '/images/salon-3.jpg'],
    features: ['كادر محترف من 6 حلاقين', 'مواقف سيارات خاصة', 'دفع بريدي موب BaridiMob', 'قهوة إيطالية مجانية'],
    workingHours: 'السبت - الخميس: 9:00 - 20:00 | الجمعة: 14:00 - 20:00',
    isOpen: true,
    featured: true,
    verified: true,
    established: 2018,
    services: [
      {
        id: 'ph-1',
        name: 'قص وتصفيف كلاسيكي',
        category: 'قص شعر',
        price: 1200,
        duration: 40,
        description: 'قص احترافي بالمقص والماكينة مع تنظيف الرقبة وغسيل بشامبو كيراتين.',
        popular: true,
      },
      {
        id: 'ph-2',
        name: 'حلاقة الذقن بالموس الساخن',
        category: 'حلاقة ذقن',
        price: 800,
        duration: 30,
        description: 'حلاقة تقليدية بالموس مع منشفة ساخنة وزيوت طبيعية مهدئة للبشرة.',
      },
      {
        id: 'ph-3',
        name: 'باقة بريستيج الشاملة',
        category: 'باقات',
        price: 2500,
        duration: 75,
        description: 'قص وتصفيف الشعر + حلاقة الذقن + تنظيف بشرة بالبخار + مساج استرخائي.',
        popular: true,
      },
      {
        id: 'ph-4',
        name: 'تدرّج عصري (Fade)',
        category: 'قص شعر',
        price: 1500,
        duration: 45,
        description: 'تدرّج دقيق بجميع أنواعه مع تحديد الخطوط وتصفيف نهائي بالواكس.',
      },
      {
        id: 'ph-5',
        name: 'تنظيف بشرة عميق',
        category: 'عناية بالبشرة',
        price: 1800,
        duration: 50,
        description: 'تنظيف عميق بالبخار، مقشّر طبيعي، وماسك مغذٍ لبشرة نضرة.',
      },
      {
        id: 'ph-6',
        name: 'صبغة شعر احترافية',
        category: 'صبغة',
        price: 2200,
        duration: 60,
        description: 'صبغة بمنتجات عالمية خالية من الأمونيا مع استشارة لون مجانية.',
      },
    ],
    barbers: [
      {
        id: 'ph-b1',
        name: 'ياسين بن عمار',
        role: 'حلاق أول',
        experience: '12 سنة خبرة',
        rating: 4.9,
        image: '/images/style-2.jpg',
        specialties: ['تدرّج Fade', 'حلاقة الموس', 'تصفيف المناسبات'],
      },
      {
        id: 'ph-b2',
        name: 'أمين بوزيد',
        role: 'أخصائي عناية بالبشرة',
        experience: '8 سنوات خبرة',
        rating: 4.8,
        image: '/images/style-1.jpg',
        specialties: ['تنظيف البشرة', 'ماسكات الوجه', 'مساج استرخائي'],
      },
    ],
    reviews: [
      {
        id: 'ph-r1',
        name: 'محمد الأمين',
        rating: 5,
        comment: 'أفضل صالون في حيدرة بلا منازع. ياسين فنان في التدرّج والحجز عبر المنصة وفّر عليّ وقت طويل.',
        date: '2026-09-12',
        service: 'تدرّج عصري (Fade)',
      },
      {
        id: 'ph-r2',
        name: 'عبد الرؤوف',
        rating: 5,
        comment: 'المكان نظيف جداً والتعامل راقٍ. باقة بريستيج الشاملة تستاهل كل دينار.',
        date: '2026-09-08',
        service: 'باقة بريستيج الشاملة',
      },
      {
        id: 'ph-r3',
        name: 'سفيان مرابط',
        rating: 4,
        comment: 'خدمة ممتازة وأسعار معقولة مقارنة بالجودة. القهوة الإيطالية لمسة جميلة.',
        date: '2026-08-29',
        service: 'قص وتصفيف كلاسيكي',
      },
    ],
  },
  {
    id: 'nour-beauty',
    slug: 'nour-beauty',
    name: 'مركز نور للجمال',
    tagline: 'جمالكِ يبدأ من هنا',
    description:
      'مركز تجميل نسائي متكامل في حي الأبيار، يقدم خدمات العناية بالشعر والبشرة والأظافر مع أحدث التقنيات العالمية وفريق نسائي محترف بالكامل.',
    type: 'نسائية',
    neighborhood: 'الأبيار',
    address: 'شارع العقيد عميروش، الأبيار، الجزائر العاصمة',
    phone: '0661 78 90 12',
    rating: 4.8,
    reviewsCount: 287,
    priceLevel: 3,
    image: '/images/salon-2.jpg',
    gallery: ['/images/salon-2.jpg', '/images/salon-4.jpg', '/images/salon-5.jpg', '/images/salon-6.jpg'],
    features: ['خصوصية تامة', 'منتجات عالمية أصلية', 'حجز خاص للعرائس', 'واي فاي فائق السرعة'],
    workingHours: 'السبت - الخميس: 9:30 - 19:30 | الجمعة: 14:00 - 19:30',
    isOpen: true,
    featured: true,
    verified: true,
    established: 2020,
    services: [
      {
        id: 'nb-1',
        name: 'قص وتصفيف الشعر',
        category: 'قص شعر',
        price: 1500,
        duration: 50,
        description: 'قص عصري حسب شكل الوجه مع تصفيف بالسيشوار ومنتجات ترطيب.',
        popular: true,
      },
      {
        id: 'nb-2',
        name: 'صبغة وهايلايت',
        category: 'صبغة',
        price: 3500,
        duration: 90,
        description: 'صبغة كاملة أو هايلايت بدرجات عصرية مع علاج بالكيراتين.',
        popular: true,
      },
      {
        id: 'nb-3',
        name: 'تنظيف بشرة هيدرافيشل',
        category: 'عناية بالبشرة',
        price: 2800,
        duration: 60,
        description: 'تنظيف عميق بتقنية الهيدرافيشل مع ترطيب مكثف ونضارة فورية.',
      },
      {
        id: 'nb-4',
        name: 'مانيكير وبديكير',
        category: 'أظافر',
        price: 1200,
        duration: 60,
        description: 'عناية كاملة بالأظافر مع تدليك وطلاء يدوي عالي الجودة.',
      },
      {
        id: 'nb-5',
        name: 'باقة العروس الملكية',
        category: 'باقات',
        price: 8500,
        duration: 180,
        description: 'تجربة متكاملة للعروس: قص وتصفيف + صبغة + تنظيف بشرة + مانيكير + مكياج.',
      },
      {
        id: 'nb-6',
        name: 'علاج الشعر التالف',
        category: 'علاج الشعر',
        price: 2000,
        duration: 45,
        description: 'علاج مكثف بالبروتين والكيراتين لإعادة الحيوية للشعر المتضرر.',
      },
    ],
    barbers: [
      {
        id: 'nb-b1',
        name: 'سارة الأحمدي',
        role: 'مصففة شعر أولى',
        experience: '10 سنوات خبرة',
        rating: 4.9,
        image: '/images/salon-2.jpg',
        specialties: ['قصات عصرية', 'صبغة وهايلايت', 'تسريحة العرائس'],
      },
      {
        id: 'nb-b2',
        name: 'نادية بلقاسم',
        role: 'أخصائية عناية بالبشرة',
        experience: '7 سنوات خبرة',
        rating: 4.8,
        image: '/images/salon-4.jpg',
        specialties: ['هيدرافيشل', 'علاج حب الشباب', 'ماسكات طبيعية'],
      },
    ],
    reviews: [
      {
        id: 'nb-r1',
        name: 'أمينة شريف',
        rating: 5,
        comment: 'سارة مبدعة بزاف، غيرتلي لون شعري وخرجت راضية 100%. المكان هادئ ونظيف.',
        date: '2026-09-14',
        service: 'صبغة وهايلايت',
      },
      {
        id: 'nb-r2',
        name: 'ليلى بن يوسف',
        rating: 5,
        comment: 'باقة العروس الملكية كانت تجربة لا تُنسى. شكراً لكل الفريق على الاحترافية.',
        date: '2026-09-02',
        service: 'باقة العروس الملكية',
      },
      {
        id: 'nb-r3',
        name: 'ريم قاسمي',
        rating: 4,
        comment: 'خدمة ممتازة في الهيدرافيشل، بشرتي ولّات نضرة من أول جلسة.',
        date: '2026-08-25',
        service: 'تنظيف بشرة هيدرافيشل',
      },
    ],
  },
  {
    id: 'maqs-centre',
    slug: 'maqs-centre',
    name: 'مقص العاصمة',
    tagline: 'الحلاقة الكلاسيكية بأجواء عصرية',
    description:
      'صالون حلاقة رجالي في وسط الجزائر العاصمة، يجمع بين الخبرة الكلاسيكية والتقنيات العصرية، بأسعار مناسبة للجميع وخدمة سريعة دون انتظار.',
    type: 'رجالية',
    neighborhood: 'الجزائر الوسطى',
    address: 'شارع الاستقلال، الجزائر الوسطى، الجزائر العاصمة',
    phone: '0770 45 67 89',
    rating: 4.7,
    reviewsCount: 512,
    priceLevel: 2,
    image: '/images/salon-3.jpg',
    gallery: ['/images/salon-3.jpg', '/images/style-1.jpg', '/images/style-3.jpg', '/images/hero-salon.jpg'],
    features: ['في قلب العاصمة', 'خدمة سريعة', 'أسعار اقتصادية', 'مفتوح 7 أيام'],
    workingHours: 'السبت - الجمعة: 8:30 - 21:00',
    isOpen: true,
    featured: true,
    verified: true,
    established: 2012,
    services: [
      {
        id: 'mc-1',
        name: 'قص شعر سريع',
        category: 'قص شعر',
        price: 700,
        duration: 25,
        description: 'قص سريع واحترافي مناسب لمن يعجل، دون التنازل عن الجودة.',
        popular: true,
      },
      {
        id: 'mc-2',
        name: 'قص ولحية',
        category: 'باقات',
        price: 1100,
        duration: 45,
        description: 'قص شعر كامل مع تهذيب وتحديد اللحية بالموس.',
        popular: true,
      },
      {
        id: 'mc-3',
        name: 'حلاقة أطفال',
        category: 'أطفال',
        price: 500,
        duration: 25,
        description: 'حلاقة لطيفة للأطفال في أجواء مريحة مع كراسي مخصصة.',
      },
      {
        id: 'mc-4',
        name: 'تهذيب اللحية',
        category: 'حلاقة ذقن',
        price: 400,
        duration: 20,
        description: 'تهذيب وتحديد اللحية بالموس مع زيت مهدئ.',
      },
      {
        id: 'mc-5',
        name: 'غسيل وتصفيف',
        category: 'تصفيف',
        price: 600,
        duration: 30,
        description: 'غسيل بشامبو منعش مع تصفيف بالسيشوار والواكس.',
      },
    ],
    barbers: [
      {
        id: 'mc-b1',
        name: 'رشيد حمادي',
        role: 'حلاق أول',
        experience: '18 سنة خبرة',
        rating: 4.8,
        image: '/images/salon-3.jpg',
        specialties: ['حلاقة كلاسيكية', 'حلاقة الموس', 'قصات الأطفال'],
      },
      {
        id: 'mc-b2',
        name: 'كريم لعمارة',
        role: 'حلاق',
        experience: '6 سنوات خبرة',
        rating: 4.6,
        image: '/images/style-1.jpg',
        specialties: ['قصات عصرية', 'تصفيف', 'تهذيب اللحية'],
      },
    ],
    reviews: [
      {
        id: 'mc-r1',
        name: 'عبد الحق',
        rating: 5,
        comment: 'خدمة سريعة وأسعار معقولة. رشيد عندو خبرة كبيرة ويخدم بذوق.',
        date: '2026-09-15',
        service: 'قص ولحية',
      },
      {
        id: 'mc-r2',
        name: 'يوسف بن علي',
        rating: 4,
        comment: 'مكان ممتاز في وسط العاصمة، قريب من الخدمة والمواصلات.',
        date: '2026-09-05',
        service: 'قص شعر سريع',
      },
      {
        id: 'mc-r3',
        name: 'محمود زروقي',
        rating: 5,
        comment: 'نحجز عبر المنصة ونلقى الكرسي واجد. هذي الخدمة كانت ناقصة في الجزائر.',
        date: '2026-08-20',
        service: 'قص ولحية',
      },
    ],
  },
  {
    id: 'elite-bab-ewar',
    slug: 'elite-bab-ewar',
    name: 'صالون النخبة باب الزوار',
    tagline: 'تجربة حلاقة عصرية للرجل العصري',
    description:
      'صالون حلاقة عصري في حي باب الزوار، مجهز بأحدث الأدوات والتجهيزات، يقدم خدمات متنوعة للرجال مع التركيز على الراحة والجودة.',
    type: 'رجالية',
    neighborhood: 'باب الزوار',
    address: 'شارع العربي بن مهيدي، باب الزوار، الجزائر العاصمة',
    phone: '0555 23 45 67',
    rating: 4.6,
    reviewsCount: 198,
    priceLevel: 2,
    image: '/images/hero-salon.jpg',
    gallery: ['/images/hero-salon.jpg', '/images/style-1.jpg', '/images/style-2.jpg', '/images/style-3.jpg'],
    features: ['أحدث الأدوات', 'أجواء شبابية', 'شاشة ترفيه', 'مشروبات مجانية'],
    workingHours: 'السبت - الخميس: 10:00 - 21:00 | الجمعة: 14:00 - 21:00',
    isOpen: true,
    featured: false,
    verified: true,
    established: 2021,
    services: [
      {
        id: 'eb-1',
        name: 'قص وتصفيف عصري',
        category: 'قص شعر',
        price: 900,
        duration: 40,
        description: 'قص عصري حسب الطلب مع تصفيف بالواكس أو الجل.',
        popular: true,
      },
      {
        id: 'eb-2',
        name: 'تدرّج احترافي',
        category: 'قص شعر',
        price: 1100,
        duration: 45,
        description: 'تدرّج دقيق بجميع الدرجات مع تحديد الخطوط.',
        popular: true,
      },
      {
        id: 'eb-3',
        name: 'حلاقة بالموس',
        category: 'حلاقة ذقن',
        price: 700,
        duration: 30,
        description: 'حلاقة تقليدية بالموس مع منشفة ساخنة.',
      },
      {
        id: 'eb-4',
        name: 'علاج تساقط الشعر',
        category: 'علاج الشعر',
        price: 1600,
        duration: 50,
        description: 'علاج مكثف لتساقط الشعر مع فيتامينات ومساج للفروة.',
      },
      {
        id: 'eb-5',
        name: 'باقة الشباب',
        category: 'باقات',
        price: 1800,
        duration: 70,
        description: 'قص + لحية + تنظيف بشرة + مساج رأس بسعر مخفّض.',
      },
    ],
    barbers: [
      {
        id: 'eb-b1',
        name: 'إسلام بوقرة',
        role: 'حلاق أول',
        experience: '9 سنوات خبرة',
        rating: 4.7,
        image: '/images/style-1.jpg',
        specialties: ['تدرّج', 'قصات شبابية', 'تصفيف'],
      },
    ],
    reviews: [
      {
        id: 'eb-r1',
        name: 'أنيس مرابط',
        rating: 5,
        comment: 'صالون نظيف ومجهز بالكامل. إسلام يخدم بسرعة ودقة.',
        date: '2026-09-10',
        service: 'تدرّج احترافي',
      },
      {
        id: 'eb-r2',
        name: 'بلال حجاج',
        rating: 4,
        comment: 'خدمة جيدة وأسعار مناسبة للطلبة.',
        date: '2026-08-30',
        service: 'قص وتصفيف عصري',
      },
    ],
  },
  {
    id: 'lamsa-bouzareah',
    slug: 'lamsa-bouzareah',
    name: 'صالون لمسة بوزريعة',
    tagline: 'لمسة جمال تليق بكِ',
    description:
      'صالون تجميل نسائي في حي بوزريعة الهادئ، يقدم خدمات العناية بالشعر والأظافر بأسعار مناسبة وأجواء عائلية دافئة.',
    type: 'نسائية',
    neighborhood: 'بوزريعة',
    address: 'شارع أول نوفمبر، بوزريعة، الجزائر العاصمة',
    phone: '0662 34 56 78',
    rating: 4.5,
    reviewsCount: 164,
    priceLevel: 2,
    image: '/images/salon-6.jpg',
    gallery: ['/images/salon-6.jpg', '/images/salon-2.jpg', '/images/salon-5.jpg', '/images/salon-4.jpg'],
    features: ['أجواء عائلية', 'أسعار مناسبة', 'منتجات طبيعية', 'خدمة منزلية'],
    workingHours: 'السبت - الخميس: 9:00 - 18:30',
    isOpen: true,
    featured: false,
    verified: true,
    established: 2019,
    services: [
      {
        id: 'lb-1',
        name: 'قص وتصفيف',
        category: 'قص شعر',
        price: 1000,
        duration: 45,
        description: 'قص وتصفيف حسب الرغبة مع غسيل وتجفيف.',
        popular: true,
      },
      {
        id: 'lb-2',
        name: 'صبغة شعر',
        category: 'صبغة',
        price: 2200,
        duration: 75,
        description: 'صبغة بدرجات متنوعة مع علاج بالزيوت الطبيعية.',
        popular: true,
      },
      {
        id: 'lb-3',
        name: 'فرد بالكيراتين',
        category: 'علاج الشعر',
        price: 4500,
        duration: 120,
        description: 'فرد طبيعي بالكيراتين للشعر المجعد أو المجعد.',
      },
      {
        id: 'lb-4',
        name: 'مانيكير بسيط',
        category: 'أظافر',
        price: 800,
        duration: 40,
        description: 'عناية أساسية بالأظافر مع تدليك اليدين.',
      },
      {
        id: 'lb-5',
        name: 'تنظيف بشرة',
        category: 'عناية بالبشرة',
        price: 1500,
        duration: 50,
        description: 'تنظيف عميق مع ماسك طبيعي مرطب.',
      },
    ],
    barbers: [
      {
        id: 'lb-b1',
        name: 'سميرة بوعلام',
        role: 'مصففة شعر',
        experience: '14 سنة خبرة',
        rating: 4.6,
        image: '/images/salon-6.jpg',
        specialties: ['صبغة', 'فرد بالكيراتين', 'قصات نسائية'],
      },
    ],
    reviews: [
      {
        id: 'lb-r1',
        name: 'نادية شريف',
        rating: 5,
        comment: 'سميرة عندها ذوق عالي وأسعارها معقولة. نحب هاد الصالون.',
        date: '2026-09-11',
        service: 'صبغة شعر',
      },
      {
        id: 'lb-r2',
        name: 'فاطمة الزهراء',
        rating: 4,
        comment: 'خدمة جيدة وأجواء مريحة، فقط الانتظار أحياناً.',
        date: '2026-08-28',
        service: 'قص وتصفيف',
      },
    ],
  },
  {
    id: 'royal-draria',
    slug: 'royal-draria',
    name: 'الصالون الملكي درارية',
    tagline: 'الفخامة والرقي في كل تفصيلة',
    description:
      'صالون ملكي فاخر في حي درارية، يقدم تجربة حلاقة واسترخاء استثنائية للرجال مع خدمات VIP ومساج احترافي ومنتجات فرنسية راقية.',
    type: 'رجالية',
    neighborhood: 'درارية',
    address: 'شارع الجيش الوطني، درارية، الجزائر العاصمة',
    phone: '0770 56 78 90',
    rating: 4.9,
    reviewsCount: 276,
    priceLevel: 3,
    image: '/images/style-1.jpg',
    gallery: ['/images/style-1.jpg', '/images/hero-salon.jpg', '/images/salon-3.jpg', '/images/style-3.jpg'],
    features: ['خدمة VIP', 'منتجات فرنسية', 'مساج احترافي', 'ركن سيجار وقهوة'],
    workingHours: 'السبت - الخميس: 10:00 - 22:00 | الجمعة: 15:00 - 22:00',
    isOpen: true,
    featured: true,
    verified: true,
    established: 2016,
    services: [
      {
        id: 'rd-1',
        name: 'الباقة الملكية الكاملة',
        category: 'باقات',
        price: 4500,
        duration: 120,
        description: 'قص + لحية + تنظيف بشرة + مساج + علاج شعر + مشروبات فاخرة.',
        popular: true,
      },
      {
        id: 'rd-2',
        name: 'قص ملكي بالمقص',
        category: 'قص شعر',
        price: 2000,
        duration: 55,
        description: 'قص حصري بالمقص فقط مع استشارة ستايل مجانية.',
        popular: true,
      },
      {
        id: 'rd-3',
        name: 'حلاقة ملكية بالموس',
        category: 'حلاقة ذقن',
        price: 1500,
        duration: 45,
        description: 'حلاقة تقليدية فاخرة مع 3 مناشف ساخنة وزيوت عطرية.',
      },
      {
        id: 'rd-4',
        name: 'مساج الوجه والرأس',
        category: 'مساج',
        price: 1800,
        duration: 40,
        description: 'مساج احترافي للاسترخاء العميق مع زيوت عطرية.',
      },
      {
        id: 'rd-5',
        name: 'علاج الشعر بالكيراتين',
        category: 'علاج الشعر',
        price: 3200,
        duration: 80,
        description: 'علاج فاخر بالكيراتين الفرنسي لإعادة بناء الشعر.',
      },
    ],
    barbers: [
      {
        id: 'rd-b1',
        name: 'عمر الشريف',
        role: 'حلاق ملكي أول',
        experience: '20 سنة خبرة',
        rating: 5.0,
        image: '/images/style-2.jpg',
        specialties: ['حلاقة الموس الملكية', 'قص بالمقص', 'استشارة ستايل'],
      },
      {
        id: 'rd-b2',
        name: 'مراد لعمامرة',
        role: 'أخصائي مساج',
        experience: '11 سنة خبرة',
        rating: 4.9,
        image: '/images/style-3.jpg',
        specialties: ['مساج الوجه', 'مساج الرأس', 'علاج التوتر'],
      },
    ],
    reviews: [
      {
        id: 'rd-r1',
        name: 'كمال بن حمادي',
        rating: 5,
        comment: 'تجربة فاخرة من الطراز الأول. الباقة الملكية تستاهل كل دينار.',
        date: '2026-09-16',
        service: 'الباقة الملكية الكاملة',
      },
      {
        id: 'rd-r2',
        name: 'طارق مزيان',
        rating: 5,
        comment: 'عمر الشريف من أفضل الحلاقين في الجزائر. خبرته باينة في كل حركة.',
        date: '2026-09-09',
        service: 'قص ملكي بالمقص',
      },
      {
        id: 'rd-r3',
        name: 'سليم براهيمي',
        rating: 5,
        comment: 'المكان راقٍ والخدمة احترافية. المساج كان مريح جداً.',
        date: '2026-08-27',
        service: 'مساج الوجه والرأس',
      },
    ],
  },
]

export const SERVICE_CATEGORIES = [
  { name: 'قص وتصفيف الشعر', icon: 'Scissors', count: 6, color: '#d4af37' },
  { name: 'حلاقة الذقن', icon: 'Sparkles', count: 5, color: '#00bb7f' },
  { name: 'العناية بالبشرة', icon: 'Flower2', count: 4, color: '#f5d77f' },
  { name: 'الصبغة والعلاج', icon: 'Palette', count: 5, color: '#c59b27' },
  { name: 'الباقات الشاملة', icon: 'Crown', count: 6, color: '#34d9a4' },
  { name: 'المانيكير والأظافر', icon: 'Hand', count: 3, color: '#e8c55f' },
]

export const PLATFORM_FEATURES = [
  {
    icon: 'Zap',
    title: 'حجز فوري في ثوانٍ',
    description: 'اختر الصالون والخدمة والموعد واحصل على تأكيد فوري بدون مكالمات هاتفية أو انتظار.',
  },
  {
    icon: 'ShieldCheck',
    title: 'صالونات موثّقة 100%',
    description: 'جميع الصالونات المميزة مراجعة وموثّقة من فريق stikini لضمان أفضل تجربة.',
  },
  {
    icon: 'BadgeDollarSign',
    title: 'أسعار واضحة وشفافة',
    description: 'تصفح أسعار الخدمات بوضوح قبل الحجز، بدون رسوم خفية أو مفاجآت.',
  },
  {
    icon: 'Star',
    title: 'تقييمات حقيقية',
    description: 'آلاف التقييمات من زبائن حقيقيين في الجزائر العاصمة تساعدك على اختيار الأنسب.',
  },
  {
    icon: 'MapPin',
    title: 'قريب منك أينما كنت',
    description: 'ابحث حسب الحي أو المنطقة في الجزائر العاصمة واعثر على أفضل الخيارات حولك.',
  },
  {
    icon: 'CalendarCheck',
    title: 'تعديل وإلغاء مرن',
    description: 'غيّر أو ألغِ حجزك بسهولة وفق سياسة الإلغاء الخاصة بكل صالون.',
  },
]

export const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'ابحث عن صالون',
    description: 'استخدم الفلاتر للعثور على الصالون المناسب حسب الحي، الخدمة أو التقييم.',
  },
  {
    step: '02',
    title: 'اختر خدمتك وموعدك',
    description: 'تصفح الخدمات والأسعار، ثم اختر التاريخ والوقت الذي يناسبك.',
  },
  {
    step: '03',
    title: 'احصل على التأكيد',
    description: 'يصلك تأكيد الحجز فوراً مع رمز تأكيد وتذكير تلقائي قبل الموعد.',
  },
  {
    step: '04',
    title: 'استمتع بتجربتك',
    description: 'قيّم تجربتك بعد الزيارة وساعد الآخرين على اختيار الأفضل.',
  },
]

export const TESTIMONIALS = [
  {
    name: 'عبد العزيز بوعلام',
    role: 'زبون منذ سنتين',
    location: 'حيدرة',
    rating: 5,
    text: 'أفضل تطبيق حجز جربته في الجزائر. وفّر عليّ وقت الانتظار، والصالونات الموثوقة ممتازة. الحجز يتم في أقل من دقيقة.',
  },
  {
    name: 'سارة قاسمي',
    role: 'زبونة دائمة',
    location: 'الأبيار',
    rating: 5,
    text: 'واجهة سهلة وسلسة، أحببت خاصية التذكيرات قبل الموعد. الآن لا أعود أنتظر في الصالون أبداً.',
  },
  {
    name: 'محمد الأمين شريف',
    role: 'صاحب صالون',
    location: 'الجزائر الوسطى',
    rating: 5,
    text: 'منصة stikini رفعت عدد حجوزاتي بشكل واضح، ولوحة الإدارة سهلة جداً. أنصح كل أصحاب الصالونات بالانضمام.',
  },
  {
    name: 'ياسين مرابط',
    role: 'زبون جديد',
    location: 'باب الزوار',
    rating: 4,
    text: 'الأسعار واضحة قبل الحجز وهذا شيء مهم. التطبيق سريع وسهل الاستخدام حتى للمبتدئين.',
  },
  {
    name: 'نادية بلحاج',
    role: 'زبونة منذ سنة',
    location: 'بوزريعة',
    rating: 5,
    text: 'جدت أفضل صالون في منطقتي عبر stikini. التقييمات الحقيقية ساعدتني كثيراً في الاختيار.',
  },
  {
    name: 'كمال زروقي',
    role: 'زبون منذ 3 سنوات',
    location: 'درارية',
    rating: 5,
    text: 'الخدمة ممتازة والفريق متجاوب. خاصية الحجز المسبق وفرت عليّ الكثير من الوقت والمكالمات.',
  },
]

export const PRICING_PLANS = [
  {
    name: 'مجاني',
    nameEn: 'Free',
    price: 0,
    period: 'للأبد',
    description: 'مثالي للزبائن الذين يريدون حجز مواعيدهم بسهولة',
    features: [
      'حجز مواعيد غير محدود',
      'تصفح جميع الصالونات',
      'قائمة الصالونات المفضلة',
      'إشعارات وتذكيرات تلقائية',
      'تقييم التجارب',
      'حساب محفوظ بشكل دائم',
    ],
    cta: 'ابدأ مجاناً',
    popular: false,
  },
  {
    name: 'احترافي',
    nameEn: 'Pro',
    price: 2900,
    period: 'شهرياً',
    description: 'لأصحاب الصالونات الذين يريدون تنمية أعمالهم',
    features: [
      'كل مزايا الباقة المجانية',
      'لوحة تحكم CRM كاملة',
      'إدارة الحجوزات والمواعيد',
      'إدارة الخدمات والأسعار',
      'إدارة فريق العمل',
      'صفحة صالون مميزة',
      'تقارير وتحليلات الأداء',
      'ظهور مميز في نتائج البحث',
    ],
    cta: 'اشترك الآن',
    popular: true,
  },
  {
    name: 'مؤسسات',
    nameEn: 'Enterprise',
    price: 9900,
    period: 'شهرياً',
    description: 'للفرق الكبيرة والسلاسل متعددة الفروع',
    features: [
      'كل مزايا الباقة الاحترافية',
      'فروع متعددة غير محدودة',
      'مدير حساب مخصص',
      'تكامل مع الأنظمة الخارجية',
      'تقارير متقدمة وتصدير',
      'تدريب مخصص للفريق',
      'API للمطورين',
      'دعم على مدار الساعة',
    ],
    cta: 'تواصل معنا',
    popular: false,
  },
]

export const FAQS = [
  {
    category: 'عام',
    question: 'هل التسجيل في المنصة مجاني؟',
    answer:
      'نعم، التسجيل مجاني بالكامل للزبائن. يمكن للصالونات الاختيار بين باقات مختلفة حسب احتياجها، مع وجود باقة مجانية تشمل جميع الأساسيات.',
  },
  {
    category: 'الحساب',
    question: 'كيف يتم حفظ معلومات حسابي؟',
    answer:
      'تحفظ stikini معلومات حسابك بشكل دائم وآمن. يمكنك إغلاق الجهاز والعودة لاحقاً وتسجيل الدخول مباشرة دون إعادة إدخال بياناتك.',
  },
  {
    category: 'الحجز',
    question: 'هل يمكنني إلغاء أو تعديل حجزي؟',
    answer:
      'نعم، يمكنك إلغاء أو تعديل حجزك بسهولة من لوحة التحكم، وفق سياسة الإلغاء الخاصة بكل صالون. ننصح بالإلغاء قبل الموعد بوقت كافٍ.',
  },
  {
    category: 'الصالونات',
    question: 'كيف أضيف صالوني إلى المنصة؟',
    answer:
      'أنشئ حساب صاحب صالون، ثم املأ استمارة إضافة الصالون بمعلوماته الكاملة — الخدمات، الأسعار، ساعات العمل، وفريق العمل — وسيظهر صالونك مباشرة.',
  },
  {
    category: 'الدفع',
    question: 'ما هي طرق الدفع المتاحة؟',
    answer:
      'تختلف طرق الدفع حسب كل صالون. معظم الصالونات تقبل الدفع نقداً، وبعضها يدعم الدفع الإلكتروني عبر BaridiMob أو البطاقة الذهبية.',
  },
  {
    category: 'الحساب',
    question: 'نسيت كلمة المرور، ماذا أفعل؟',
    answer:
      'يمكنك استعادة كلمة المرور بسهولة من صفحة تسجيل الدخول عبر خيار "نسيت كلمة المرور؟" وسيتم إرسال رابط الاستعادة إلى بريدك الإلكتروني.',
  },
  {
    category: 'الحجز',
    question: 'هل أحتاج إلى حساب لحجز موعد؟',
    answer:
      'نعم، إنشاء حساب مجاني يأخذ أقل من دقيقة ويسمح لك بحفظ حجوزاتك، تلقي التذكيرات، وإدارة مواعيدك بسهولة.',
  },
  {
    category: 'الصالونات',
    question: 'هل هناك رسوم على الحجوزات؟',
    answer:
      'لا، المنصة لا تأخذ أي رسوم على الحجوزات من الزبائن. تدفع فقط تكلفة الخدمة مباشرة في الصالون.',
  },
]

export const STATS = [
  { value: '12,500+', label: 'زبون نشط', icon: 'Users' },
  { value: '480+', label: 'صالون موثّق', icon: 'Store' },
  { value: '95%', label: 'رضا العملاء', icon: 'Heart' },
  { value: '30 ثانية', label: 'متوسط وقت الحجز', icon: 'Clock' },
]

export const ALGIERS_AREAS = [
  'الجزائر الوسطى',
  'حيدرة',
  'الأبيار',
  'بوزريعة',
  'درارية',
  'الشراقة',
  'باب الزوار',
  'الرويبة',
  'الحراش',
  'القبة',
  'كولوش',
  'برج الكيفان',
  'بئر مراد رايس',
  'وادي السمار',
  'الدار البيضاء',
  'عين البنيان',
  'زرالدة',
  'المرسى',
  'حسين داي',
  'القصبة',
]
